opam-version: "1"
version: "4.01.0"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.01/ocaml-4.01.0.tar.gz"
patches: ["https://github.com/diml/ocaml/commit/c83068bd7b95b3e29b2edc9410cea4b14625f3aa.diff"]
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
